// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbBCdRmmXQnFk3p4gZDG_jsFsFDcoPJvI',
    appId: '1:1095863216109:web:ebee558734c095245fa9e4',
    messagingSenderId: '1095863216109',
    projectId: 'legalease-backend',
    authDomain: 'legalease-backend.firebaseapp.com',
    storageBucket: 'legalease-backend.appspot.com',
    measurementId: 'G-51Q7YYKPYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3xztinw3HDlf6DC05uxTs2p2G8KPld-A',
    appId: '1:1095863216109:android:40fa20d8d328bda95fa9e4',
    messagingSenderId: '1095863216109',
    projectId: 'legalease-backend',
    storageBucket: 'legalease-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKIsMHITiLzFbfesM6aeqapHggLXMrQ0A',
    appId: '1:1095863216109:ios:32bfb5c4180caa0c5fa9e4',
    messagingSenderId: '1095863216109',
    projectId: 'legalease-backend',
    storageBucket: 'legalease-backend.appspot.com',
    iosClientId: '1095863216109-oeit9sk8cpqvdio0c1h7nfqdak4rpo0n.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKIsMHITiLzFbfesM6aeqapHggLXMrQ0A',
    appId: '1:1095863216109:ios:37faa27de3b8d1b25fa9e4',
    messagingSenderId: '1095863216109',
    projectId: 'legalease-backend',
    storageBucket: 'legalease-backend.appspot.com',
    iosClientId: '1095863216109-umqmvr7fr30m2d171hvajif690llbi6a.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
